#!/usr/bin/env python3
"""
Generate the function lookup table (section_table.cpp) from symbols.toml
and the generated funcs.h. This creates the SectionTableEntry data structures
needed by librecomp to map VRAM addresses to recompiled function pointers.
"""
import re
import sys

SYMBOLS_PATH = "symbols.toml"
FUNCS_H_PATH = "RecompiledFuncs/funcs.h"
OUTPUT_PATH = "src/section_table.cpp"

def parse_symbols(path):
    """Parse symbols.toml to get section info and function list."""
    with open(path, 'r') as f:
        text = f.read()

    # Parse section info
    section_match = re.search(
        r'\[\[section\]\]\s*\n\s*name\s*=\s*"([^"]+)"\s*\n\s*rom\s*=\s*(0x[0-9A-Fa-f]+)\s*\n\s*vram\s*=\s*(0x[0-9A-Fa-f]+)\s*\n\s*size\s*=\s*(0x[0-9A-Fa-f]+)',
        text
    )
    if not section_match:
        print("ERROR: Could not find section info in symbols.toml")
        sys.exit(1)

    section_name = section_match.group(1)
    section_rom = int(section_match.group(2), 16)
    section_vram = int(section_match.group(3), 16)
    section_size = int(section_match.group(4), 16)

    # Parse functions
    func_pattern = re.compile(
        r'\[\[section\.functions\]\]\s*\n\s*(?:#[^\n]*\n\s*)?name\s*=\s*"([^"]+)"\s*\n\s*vram\s*=\s*(0x[0-9A-Fa-f]+)\s*\n\s*size\s*=\s*(0x[0-9A-Fa-f]+)',
        re.MULTILINE
    )

    functions = []
    for m in func_pattern.finditer(text):
        name = m.group(1)
        vram = int(m.group(2), 16)
        size = int(m.group(3), 16)
        offset = vram - section_vram
        functions.append((name, vram, size, offset))

    return {
        'name': section_name,
        'rom': section_rom,
        'vram': section_vram,
        'size': section_size,
        'functions': functions
    }

def parse_funcs_h(path):
    """Parse funcs.h to get the list of actually generated function names."""
    with open(path, 'r') as f:
        text = f.read()

    # Pattern: void func_name(uint8_t* rdram, recomp_context* ctx);
    pattern = re.compile(r'void\s+(\w+)\s*\(')
    return set(pattern.findall(text))

def main():
    section = parse_symbols(SYMBOLS_PATH)
    generated_funcs = parse_funcs_h(FUNCS_H_PATH)

    print(f"Section: {section['name']}")
    print(f"  ROM: 0x{section['rom']:X}, VRAM: 0x{section['vram']:X}, Size: 0x{section['size']:X}")
    print(f"  Functions in symbols.toml: {len(section['functions'])}")
    print(f"  Functions in funcs.h: {len(generated_funcs)}")

    # Match functions - only include those that exist in both
    matched = []
    missing = []
    for name, vram, size, offset in section['functions']:
        if name in generated_funcs:
            matched.append((name, vram, size, offset))
        else:
            missing.append((name, vram))

    # Also check for static_0_ functions in funcs.h that aren't in symbols.toml
    symbol_names = {f[0] for f in section['functions']}
    extra_generated = []
    for func_name in sorted(generated_funcs):
        if func_name not in symbol_names:
            extra_generated.append(func_name)

    print(f"  Matched: {len(matched)}")
    print(f"  Missing from funcs.h: {len(missing)}")
    if extra_generated:
        print(f"  Extra in funcs.h (static_0_ etc): {len(extra_generated)}")
        for name in extra_generated:
            print(f"    {name}")

    # Generate the C++ source file
    with open(OUTPUT_PATH, 'w') as f:
        f.write('// Auto-generated by gen_lookup_table.py\n')
        f.write('// Maps VRAM addresses to recompiled function pointers\n')
        f.write('#include "recomp.h"\n')
        f.write('#include "librecomp/sections.h"\n')
        f.write('#include "funcs.h"\n')
        f.write('\n')

        # Emit the function entries array
        f.write(f'static FuncEntry section_funcs[] = {{\n')
        for name, vram, size, offset in matched:
            f.write(f'    {{ {name}, 0x{offset:X}, 0x{size:X} }},\n')

        # Also add any extra static functions from funcs.h
        for func_name in extra_generated:
            # Try to parse VRAM from name (static_0_XXXXXXXX)
            m = re.match(r'static_0_([0-9A-Fa-f]+)', func_name)
            if m:
                vram = int(m.group(1), 16)
                offset = vram - section['vram']
                f.write(f'    {{ {func_name}, 0x{offset:X}, 0x0 }},  // auto-detected\n')

        f.write('};\n\n')

        # Emit the section table entry
        f.write(f'SectionTableEntry section_table[] = {{\n')
        f.write(f'    {{\n')
        f.write(f'        0x{section["rom"]:X},  // rom_addr\n')
        f.write(f'        0x{section["vram"]:X},  // ram_addr\n')
        f.write(f'        0x{section["size"]:X},  // size\n')
        f.write(f'        section_funcs,  // funcs\n')
        total_funcs = len(matched) + len([n for n in extra_generated if n.startswith('static_0_')])
        f.write(f'        {total_funcs},  // num_funcs\n')
        f.write(f'        nullptr,  // relocs (none for static code)\n')
        f.write(f'        0,  // num_relocs\n')
        f.write(f'        0,  // index\n')
        f.write(f'    }},\n')
        f.write(f'}};\n\n')

        f.write(f'extern const size_t num_sections = 1;\n')

    print(f"\nGenerated {OUTPUT_PATH}")
    print(f"  {total_funcs} function entries")

if __name__ == "__main__":
    main()
