// Auto-generated by gen_lookup_table.py
// Maps VRAM addresses to recompiled function pointers
#include "recomp.h"
#include "librecomp/sections.h"
#include "funcs.h"

static FuncEntry section_funcs[] = {
    { recomp_entrypoint, 0x0, 0x70 },
    { boot_init, 0x70, 0x9C },
    { set_debug_level, 0x120, 0xC },
    { set_debug_value, 0x12C, 0xC },
    { get_debug_value, 0x138, 0xC },
    { nop_stub, 0x144, 0x8 },
    { save_arg_to_stack, 0x14C, 0x8 },
    { bzero_func, 0x154, 0x60 },
    { func_800005B4, 0x1B4, 0x3DC },
    { func_80000990, 0x590, 0x170 },
    { func_80000B00, 0x700, 0x280 },
    { func_80000D80, 0x980, 0x114 },
    { func_80000E94, 0xA94, 0x9D0 },
    { func_80001864, 0x1464, 0x4D0 },
    { func_80001D34, 0x1934, 0x14C },
    { func_80001E80, 0x1A80, 0x258 },
    { func_800020D8, 0x1CD8, 0x5E4 },
    { func_800026BC, 0x22BC, 0x528 },
    { func_80002BE4, 0x27E4, 0x258 },
    { func_80002E3C, 0x2A3C, 0x1C0 },
    { func_80002FFC, 0x2BFC, 0x34C },
    { func_80003348, 0x2F48, 0x274 },
    { func_800035BC, 0x31BC, 0x32C },
    { func_800038E8, 0x34E8, 0x25C },
    { func_80003B44, 0x3744, 0xB4 },
    { func_80003BF8, 0x37F8, 0x254 },
    { func_80003E4C, 0x3A4C, 0x1CC },
    { func_80004018, 0x3C18, 0x158 },
    { func_80004170, 0x3D70, 0x500 },
    { func_80004670, 0x4270, 0x94 },
    { func_80004704, 0x4304, 0x2F8 },
    { func_800049FC, 0x45FC, 0x400 },
    { func_80004DFC, 0x49FC, 0x1B4 },
    { func_80004FB0, 0x4BB0, 0x184 },
    { func_80005134, 0x4D34, 0x10C },
    { func_80005240, 0x4E40, 0xA1C },
    { func_80005C5C, 0x585C, 0x78 },
    { func_80005CD4, 0x58D4, 0xD4 },
    { func_80005DA8, 0x59A8, 0x1AC },
    { func_80005F54, 0x5B54, 0x1CC },
    { func_80006120, 0x5D20, 0xE0 },
    { func_80006200, 0x5E00, 0x26C },
    { func_8000646C, 0x606C, 0xB0 },
    { func_8000651C, 0x611C, 0x274 },
    { math_vector_func_80006790, 0x6390, 0xB8 },
    { func_80006848, 0x6448, 0x3B8 },
    { func_80006C00, 0x6800, 0x15C },
    { func_80006D5C, 0x695C, 0x11C },
    { func_80006E78, 0x6A78, 0x48 },
    { func_80006EC0, 0x6AC0, 0xA0 },
    { func_80006F60, 0x6B60, 0x84 },
    { func_80006FE4, 0x6BE4, 0x50 },
    { func_80007034, 0x6C34, 0x1E4 },
    { func_80007218, 0x6E18, 0x19C },
    { func_800073B4, 0x6FB4, 0xD4 },
    { func_80007488, 0x7088, 0x10C },
    { func_80007594, 0x7194, 0x194 },
    { func_80007728, 0x7328, 0xF8 },
    { func_80007820, 0x7420, 0x268 },
    { func_80007A88, 0x7688, 0x90 },
    { func_80007B18, 0x7718, 0x22C },
    { func_80007D44, 0x7944, 0x13C },
    { func_80007E80, 0x7A80, 0xDC },
    { func_80007F5C, 0x7B5C, 0x6C },
    { func_80007FC8, 0x7BC8, 0xC8 },
    { func_80008090, 0x7C90, 0x4C0 },
    { func_80008550, 0x8150, 0xC0 },
    { func_80008610, 0x8210, 0xE8 },
    { func_800086F8, 0x82F8, 0x68 },
    { func_80008760, 0x8360, 0x3BC },
    { func_80008B1C, 0x871C, 0x58 },
    { func_80008B74, 0x8774, 0x50 },
    { func_80008BC4, 0x87C4, 0x94 },
    { func_80008C58, 0x8858, 0x2D8 },
    { func_80008F30, 0x8B30, 0x280 },
    { func_800091B0, 0x8DB0, 0x13C },
    { func_800092EC, 0x8EEC, 0xC4 },
    { func_800093B0, 0x8FB0, 0x1D0 },
    { func_80009580, 0x9180, 0x184 },
    { func_80009704, 0x9304, 0x40 },
    { func_80009744, 0x9344, 0xE4 },
    { func_80009828, 0x9428, 0x364 },
    { func_80009B8C, 0x978C, 0x80 },
    { func_80009C0C, 0x980C, 0x360 },
    { func_80009F6C, 0x9B6C, 0x3C },
    { func_80009FA8, 0x9BA8, 0x388 },
    { func_8000A330, 0x9F30, 0x1A8 },
    { func_8000A4D8, 0xA0D8, 0x64 },
    { func_8000A53C, 0xA13C, 0x754 },
    { func_8000AC90, 0xA890, 0x34 },
    { func_8000ACC4, 0xA8C4, 0x41C },
    { func_8000B0E0, 0xACE0, 0x174 },
    { func_8000B254, 0xAE54, 0x738 },
    { func_8000B98C, 0xB58C, 0x1EC },
    { func_8000BB78, 0xB778, 0x9C8 },
    { func_8000C540, 0xC140, 0x23C },
    { func_8000C77C, 0xC37C, 0x4A0 },
    { func_8000CC1C, 0xC81C, 0x514 },
    { func_8000D130, 0xCD30, 0x3B8 },
    { func_8000D4E8, 0xD0E8, 0x104 },
    { func_8000D5EC, 0xD1EC, 0x1F0 },
    { func_8000D7DC, 0xD3DC, 0x3C },
    { func_8000D818, 0xD418, 0x8C },
    { func_8000D8A4, 0xD4A4, 0x70 },
    { func_8000D914, 0xD514, 0x54 },
    { func_8000D968, 0xD568, 0x48 },
    { func_8000D9B0, 0xD5B0, 0xCEC },
    { func_8000E69C, 0xE29C, 0xB8 },
    { func_8000E754, 0xE354, 0x9C },
    { func_8000E7F0, 0xE3F0, 0xD4 },
    { func_8000E8C4, 0xE4C4, 0x188 },
    { func_8000EA4C, 0xE64C, 0x19C },
    { func_8000EBE8, 0xE7E8, 0x300 },
    { func_8000EEE8, 0xEAE8, 0x1F4 },
    { func_8000F0DC, 0xECDC, 0x4CC },
    { func_8000F5A8, 0xF1A8, 0x484 },
    { func_8000FA2C, 0xF62C, 0x654 },
    { func_80010080, 0xFC80, 0x55C },
    { func_800105DC, 0x101DC, 0x558 },
    { func_80010B34, 0x10734, 0x36C },
    { func_80010EA0, 0x10AA0, 0x848 },
    { func_800116E8, 0x112E8, 0xBC },
    { func_800117A4, 0x113A4, 0x4C },
    { func_800117F0, 0x113F0, 0xA0 },
    { func_80011890, 0x11490, 0x68 },
    { func_800118F8, 0x114F8, 0x48 },
    { func_80011940, 0x11540, 0x1D8 },
    { func_80011B18, 0x11718, 0xC4 },
    { func_80011BDC, 0x117DC, 0x100 },
    { func_80011CDC, 0x118DC, 0x84 },
    { func_80011D60, 0x11960, 0x144 },
    { func_80011EA4, 0x11AA4, 0x740 },
    { func_800125E4, 0x121E4, 0x3D8 },
    { func_800129BC, 0x125BC, 0x28 },
    { func_800129E4, 0x125E4, 0x178 },
    { func_80012B5C, 0x1275C, 0x94 },
    { func_80012BF0, 0x127F0, 0x11D0 },
    { func_80013DC0, 0x139C0, 0x438 },
    { func_800141F8, 0x13DF8, 0x370 },
    { func_80014568, 0x14168, 0x770 },
    { func_80014CD8, 0x148D8, 0x48 },
    { func_80014D20, 0x14920, 0x34 },
    { func_80014D54, 0x14954, 0x1D8 },
    { func_80014F2C, 0x14B2C, 0x2B4 },
    { func_800151E0, 0x14DE0, 0x250 },
    { math_float_func, 0x15030, 0x48 },
    { math_vector_func_80015478, 0x15078, 0x58 },
    { math_vector_func_800154D0, 0x150D0, 0x7C },
    { func_8001554C, 0x1514C, 0x1DC },
    { func_80015728, 0x15328, 0x50C },
    { func_80015C34, 0x15834, 0x498 },
    { func_800160CC, 0x15CCC, 0x194 },
    { func_80016260, 0x15E60, 0x584 },
    { func_800167E4, 0x163E4, 0x23C },
    { func_80016A20, 0x16620, 0x1EC },
    { math_vector_func_80016C0C, 0x1680C, 0xB8 },
    { func_80016CC4, 0x168C4, 0x12C },
    { func_80016DF0, 0x169F0, 0x11C },
    { func_80016F0C, 0x16B0C, 0x330 },
    { func_8001723C, 0x16E3C, 0x110 },
    { func_8001734C, 0x16F4C, 0x110 },
    { math_vector_func_8001745C, 0x1705C, 0x5C },
    { func_800174B8, 0x170B8, 0x128 },
    { func_800175E0, 0x171E0, 0x244 },
    { func_80017824, 0x17424, 0xA0 },
    { func_800178C4, 0x174C4, 0x128 },
    { func_800179EC, 0x175EC, 0xD4 },
    { math_vector_func_80017AC0, 0x176C0, 0x7C },
    { func_80017B3C, 0x1773C, 0x1DC },
    { func_80017D18, 0x17918, 0x24C },
    { func_80017F64, 0x17B64, 0x6C },
    { func_80017FD0, 0x17BD0, 0x1EC },
    { render_submit, 0x17DBC, 0x19C4 },
    { func_80019B80, 0x19780, 0x3C },
    { func_80019BBC, 0x197BC, 0x854 },
    { func_8001A410, 0x1A010, 0x1FF4 },
    { func_8001C404, 0x1C004, 0x194C },
    { func_8001DD50, 0x1D950, 0x58 },
    { func_8001DDA8, 0x1D9A8, 0x920 },
    { func_8001E6C8, 0x1E2C8, 0xDC4 },
    { func_8001F48C, 0x1F08C, 0x1E08 },
    { func_80021294, 0x20E94, 0xCF8 },
    { func_80021F8C, 0x21B8C, 0x80C },
    { func_80022798, 0x22398, 0x20DC },
    { func_80024874, 0x24474, 0x8D4 },
    { func_80025148, 0x24D48, 0x1508 },
    { func_80026650, 0x26250, 0x4EC },
    { func_80026B3C, 0x2673C, 0x614 },
    { func_80027150, 0x26D50, 0x8C8 },
    { func_80027A18, 0x27618, 0x31C },
    { func_80027D34, 0x27934, 0x33C },
    { func_80028070, 0x27C70, 0x68 },
    { func_800280D8, 0x27CD8, 0x248 },
    { func_80028320, 0x27F20, 0x178 },
    { func_80028498, 0x28098, 0x8C8 },
    { func_80028D60, 0x28960, 0x128 },
    { func_80028E88, 0x28A88, 0x22C },
    { func_800290B4, 0x28CB4, 0x27C },
    { func_80029330, 0x28F30, 0x16C },
    { func_8002949C, 0x2909C, 0x1A0 },
    { func_8002963C, 0x2923C, 0x6FC },
    { func_80029D38, 0x29938, 0xAAC },
    { func_8002A7E4, 0x2A3E4, 0x58C },
    { func_8002AD70, 0x2A970, 0x28C },
    { func_8002AFFC, 0x2ABFC, 0x3D0 },
    { func_8002B3CC, 0x2AFCC, 0x1A8 },
    { func_8002B574, 0x2B174, 0x630 },
    { func_8002BBA4, 0x2B7A4, 0xBE8 },
    { func_8002C78C, 0x2C38C, 0x4A8 },
    { func_8002CC34, 0x2C834, 0x414 },
    { func_8002D048, 0x2CC48, 0x488 },
    { func_8002D4D0, 0x2D0D0, 0x27C },
    { func_8002D74C, 0x2D34C, 0x2DC },
    { func_8002DA28, 0x2D628, 0xF8 },
    { func_8002DB20, 0x2D720, 0xB8 },
    { func_8002DBD8, 0x2D7D8, 0x11C },
    { func_8002DCF4, 0x2D8F4, 0x88 },
    { func_8002DD7C, 0x2D97C, 0x240 },
    { func_8002DFBC, 0x2DBBC, 0x78 },
    { func_8002E034, 0x2DC34, 0x88 },
    { func_8002E0BC, 0x2DCBC, 0x78 },
    { func_8002E134, 0x2DD34, 0x1C8 },
    { func_8002E2FC, 0x2DEFC, 0x1B8 },
    { func_8002E4B4, 0x2E0B4, 0x94 },
    { func_8002E548, 0x2E148, 0x8C },
    { func_8002E5D4, 0x2E1D4, 0x70 },
    { func_8002E644, 0x2E244, 0xB0 },
    { func_8002E6F4, 0x2E2F4, 0x7C },
    { func_8002E770, 0x2E370, 0xBC },
    { func_8002E82C, 0x2E42C, 0xBC },
    { func_8002E8E8, 0x2E4E8, 0x148 },
    { func_8002EA30, 0x2E630, 0x270 },
    { func_8002ECA0, 0x2E8A0, 0x38C },
    { func_8002F02C, 0x2EC2C, 0x48 },
    { func_8002F074, 0x2EC74, 0x80 },
    { func_8002F0F4, 0x2ECF4, 0x58 },
    { func_8002F14C, 0x2ED4C, 0x48 },
    { func_8002F194, 0x2ED94, 0x60 },
    { func_8002F1F4, 0x2EDF4, 0x2DC },
    { main_init, 0x2F0D0, 0x80 },
    { func_8002F550, 0x2F150, 0x200 },
    { func_8002F750, 0x2F350, 0x290 },
    { func_8002F9E0, 0x2F5E0, 0x2C },
    { func_8002FA0C, 0x2F60C, 0xC4 },
    { func_8002FAD0, 0x2F6D0, 0x48 },
    { func_8002FB18, 0x2F718, 0x78 },
    { func_8002FB90, 0x2F790, 0xC8 },
    { func_8002FC58, 0x2F858, 0x80 },
    { func_8002FCD8, 0x2F8D8, 0xE4 },
    { func_8002FDBC, 0x2F9BC, 0x48 },
    { func_8002FE04, 0x2FA04, 0xE0 },
    { func_8002FEE4, 0x2FAE4, 0x54 },
    { func_8002FF38, 0x2FB38, 0x1F8 },
    { func_80030130, 0x2FD30, 0x24 },
    { racer_update_speed, 0x2FD54, 0x20 },
    { func_80030174, 0x2FD74, 0x100 },
    { func_80030274, 0x2FE74, 0x24 },
    { func_80030298, 0x2FE98, 0x6C },
    { func_80030304, 0x2FF04, 0x24 },
    { func_80030328, 0x2FF28, 0x114 },
    { func_8003043C, 0x3003C, 0x70 },
    { func_800304AC, 0x300AC, 0x148 },
    { func_800305F4, 0x301F4, 0x370 },
    { func_80030964, 0x30564, 0x22C },
    { func_80030B90, 0x30790, 0x78 },
    { func_80030C08, 0x30808, 0x98 },
    { func_80030CA0, 0x308A0, 0x208 },
    { func_80030EA8, 0x30AA8, 0xF8 },
    { func_80030FA0, 0x30BA0, 0x6C },
    { func_8003100C, 0x30C0C, 0x128 },
    { func_80031134, 0x30D34, 0x1F0 },
    { func_80031324, 0x30F24, 0xE8 },
    { func_8003140C, 0x3100C, 0x154 },
    { func_80031560, 0x31160, 0x78 },
    { func_800315D8, 0x311D8, 0x68 },
    { func_80031640, 0x31240, 0x68 },
    { func_800316A8, 0x312A8, 0x27C },
    { func_80031924, 0x31524, 0x34 },
    { func_80031958, 0x31558, 0x74 },
    { func_800319CC, 0x315CC, 0x28 },
    { func_800319F4, 0x315F4, 0xBC },
    { func_80031AB0, 0x316B0, 0xC0 },
    { func_80031B70, 0x31770, 0x4C },
    { func_80031BBC, 0x317BC, 0x48 },
    { func_80031C04, 0x31804, 0x1328 },
    { func_80032F2C, 0x32B2C, 0xE4 },
    { func_80033010, 0x32C10, 0x130 },
    { func_80033140, 0x32D40, 0x450 },
    { func_80033590, 0x33190, 0xCC },
    { func_8003365C, 0x3325C, 0x124 },
    { func_80033780, 0x33380, 0xF8 },
    { func_80033878, 0x33478, 0xB0 },
    { func_80033928, 0x33528, 0x64 },
    { func_8003398C, 0x3358C, 0x240 },
    { func_80033BCC, 0x337CC, 0x928 },
    { func_800344F4, 0x340F4, 0x15C },
    { func_80034650, 0x34250, 0x208 },
    { func_80034858, 0x34458, 0xFC },
    { func_80034954, 0x34554, 0x78 },
    { func_800349CC, 0x345CC, 0x45C },
    { func_80034E28, 0x34A28, 0x52C },
    { func_80035354, 0x34F54, 0x244 },
    { func_80035598, 0x35198, 0x3BC },
    { func_80035954, 0x35554, 0x29C },
    { func_80035BF0, 0x357F0, 0x724 },
    { func_80036314, 0x35F14, 0x3D0 },
    { func_800366E4, 0x362E4, 0x338 },
    { func_80036A1C, 0x3661C, 0x57C },
    { func_80036F98, 0x36B98, 0x52C },
    { func_800374C4, 0x370C4, 0x7C8 },
    { func_80037C8C, 0x3788C, 0x210 },
    { func_80037E9C, 0x37A9C, 0x3F8 },
    { func_80038294, 0x37E94, 0xF4 },
    { func_80038388, 0x37F88, 0x470 },
    { func_800387F8, 0x383F8, 0x158 },
    { func_80038950, 0x38550, 0x2F8 },
    { func_80038C48, 0x38848, 0x114 },
    { func_80038D5C, 0x3895C, 0x428 },
    { func_80039184, 0x38D84, 0x70 },
    { func_800391F4, 0x38DF4, 0xB8 },
    { func_800392AC, 0x38EAC, 0x3C },
    { func_800392E8, 0x38EE8, 0x34 },
    { func_8003931C, 0x38F1C, 0x24 },
    { func_80039340, 0x38F40, 0x9C },
    { func_800393DC, 0x38FDC, 0x9C },
    { func_80039478, 0x39078, 0x1D4 },
    { func_8003964C, 0x3924C, 0x94 },
    { func_800396E0, 0x392E0, 0x88 },
    { func_80039768, 0x39368, 0xC0 },
    { func_80039828, 0x39428, 0x68 },
    { func_80039890, 0x39490, 0x30 },
    { func_800398C0, 0x394C0, 0x138 },
    { func_800399F8, 0x395F8, 0x40 },
    { func_80039A38, 0x39638, 0x138 },
    { func_80039B70, 0x39770, 0x1C4 },
    { func_80039D34, 0x39934, 0x18C },
    { func_80039EC0, 0x39AC0, 0x580 },
    { func_8003A440, 0x3A040, 0x38 },
    { func_8003A478, 0x3A078, 0x164 },
    { func_8003A5DC, 0x3A1DC, 0x5C4 },
    { func_8003ABA0, 0x3A7A0, 0x2C4 },
    { func_8003AE64, 0x3AA64, 0x1C8 },
    { func_8003B02C, 0x3AC2C, 0x158 },
    { func_8003B184, 0x3AD84, 0x6C },
    { func_8003B1F0, 0x3ADF0, 0x134 },
    { func_8003B324, 0x3AF24, 0x2120 },
    { func_8003D444, 0x3D044, 0xD50 },
    { func_8003E194, 0x3DD94, 0x58 },
    { func_8003E1EC, 0x3DDEC, 0xD4 },
    { func_8003E2C0, 0x3DEC0, 0x2DC },
    { func_8003E59C, 0x3E19C, 0x2D4 },
    { func_8003E870, 0x3E470, 0xB0 },
    { func_8003E920, 0x3E520, 0xB8 },
    { func_8003E9D8, 0x3E5D8, 0x58 },
    { func_8003EA30, 0x3E630, 0x54 },
    { func_8003EA84, 0x3E684, 0x1BC },
    { collision_check, 0x3E840, 0x70 },
    { func_8003ECB0, 0x3E8B0, 0x64 },
    { func_8003ED14, 0x3E914, 0x60 },
    { func_8003ED74, 0x3E974, 0x60 },
    { func_8003EDD4, 0x3E9D4, 0x74 },
    { func_8003EE48, 0x3EA48, 0x68 },
    { func_8003EEB0, 0x3EAB0, 0x64 },
    { func_8003EF14, 0x3EB14, 0x64 },
    { func_8003EF78, 0x3EB78, 0x64 },
    { func_8003EFDC, 0x3EBDC, 0x3AC },
    { func_8003F388, 0x3EF88, 0xEC },
    { func_8003F474, 0x3F074, 0xEC },
    { func_8003F560, 0x3F160, 0xEC },
    { func_8003F64C, 0x3F24C, 0xD0 },
    { func_8003F71C, 0x3F31C, 0x1E0 },
    { func_8003F8FC, 0x3F4FC, 0x78 },
    { func_8003F974, 0x3F574, 0x28 },
    { func_8003F99C, 0x3F59C, 0x88 },
    { func_8003FA24, 0x3F624, 0x110 },
    { func_8003FB34, 0x3F734, 0xA8 },
    { func_8003FBDC, 0x3F7DC, 0xB8 },
    { func_8003FC94, 0x3F894, 0xE8 },
    { func_8003FD7C, 0x3F97C, 0x50 },
    { func_8003FDCC, 0x3F9CC, 0x2A0 },
    { func_8004006C, 0x3FC6C, 0x190 },
    { func_800401FC, 0x3FDFC, 0x6D4 },
    { func_800408D0, 0x404D0, 0x418 },
    { func_80040CE8, 0x408E8, 0x370 },
    { func_80041058, 0x40C58, 0x7C },
    { func_800410D4, 0x40CD4, 0x140 },
    { func_80041214, 0x40E14, 0x7A8 },
    { func_800419BC, 0x415BC, 0x30 },
    { func_800419EC, 0x415EC, 0x328 },
    { func_80041D14, 0x41914, 0xEA4 },
    { func_80042BB8, 0x427B8, 0x33C },
    { func_80042EF4, 0x42AF4, 0x6A4 },
    { func_80043598, 0x43198, 0x324 },
    { func_800438BC, 0x434BC, 0x2B0 },
    { func_80043B6C, 0x4376C, 0x164 },
    { func_80043CD0, 0x438D0, 0x510 },
    { func_800441E0, 0x43DE0, 0x104 },
    { func_800442E4, 0x43EE4, 0x8C },
    { func_80044370, 0x43F70, 0xAC },
    { func_8004441C, 0x4401C, 0x94 },
    { func_800444B0, 0x440B0, 0x1B8 },
    { func_80044668, 0x44268, 0x99C },
    { func_80045004, 0x44C04, 0x310 },
    { func_80045314, 0x44F14, 0x198 },
    { func_800454AC, 0x450AC, 0xDC },
    { func_80045588, 0x45188, 0x700 },
    { func_80045C88, 0x45888, 0x118 },
    { func_80045DA0, 0x459A0, 0xE0 },
    { func_80045E80, 0x45A80, 0xE0 },
    { func_80045F60, 0x45B60, 0x1BC },
    { func_8004611C, 0x45D1C, 0x214 },
    { func_80046330, 0x45F30, 0x1B8 },
    { func_800464E8, 0x460E8, 0x188 },
    { audio_play_sfx, 0x46270, 0x11C },
    { func_8004678C, 0x4638C, 0x6C },
    { func_800467F8, 0x463F8, 0x78 },
    { func_80046870, 0x46470, 0x104 },
    { func_80046974, 0x46574, 0x450 },
    { func_80046DC4, 0x469C4, 0xBE8 },
    { func_800479AC, 0x475AC, 0xCC },
    { func_80047A78, 0x47678, 0x14FC },
    { func_80048F74, 0x48B74, 0x55C },
    { func_800494D0, 0x490D0, 0x744 },
    { func_80049C14, 0x49814, 0x758 },
    { func_8004A36C, 0x49F6C, 0x248 },
    { func_8004A5B4, 0x4A1B4, 0xF0 },
    { func_8004A6A4, 0x4A2A4, 0xDC },
    { func_8004A780, 0x4A380, 0x78 },
    { func_8004A7F8, 0x4A3F8, 0x88 },
    { func_8004A880, 0x4A480, 0x5F4 },
    { func_8004AE74, 0x4AA74, 0xEC },
    { func_8004AF60, 0x4AB60, 0x74 },
    { func_8004AFD4, 0x4ABD4, 0xB0 },
    { func_8004B084, 0x4AC84, 0x108 },
    { func_8004B18C, 0x4AD8C, 0x270 },
    { func_8004B3FC, 0x4AFFC, 0x16C },
    { func_8004B568, 0x4B168, 0x180 },
    { func_8004B6E8, 0x4B2E8, 0x180 },
    { func_8004B868, 0x4B468, 0x260 },
    { func_8004BAC8, 0x4B6C8, 0x334 },
    { func_8004BDFC, 0x4B9FC, 0x94 },
    { func_8004BE90, 0x4BA90, 0xBC0 },
    { func_8004CA50, 0x4C650, 0x11BC },
    { func_8004DC0C, 0x4D80C, 0x428 },
    { math_vector_func_8004E034, 0x4DC34, 0x6C },
    { func_8004E0A0, 0x4DCA0, 0x454 },
    { func_8004E4F4, 0x4E0F4, 0x514 },
    { func_8004EA08, 0x4E608, 0x84C },
    { func_8004F254, 0x4EE54, 0x104 },
    { func_8004F358, 0x4EF58, 0x438 },
    { func_8004F790, 0x4F390, 0x818 },
    { func_8004FFA8, 0x4FBA8, 0x2E8 },
    { func_80050290, 0x4FE90, 0x158 },
    { func_800503E8, 0x4FFE8, 0x68 },
    { func_80050450, 0x50050, 0x13C },
    { func_8005058C, 0x5018C, 0xD0 },
    { func_8005065C, 0x5025C, 0x38C },
    { func_800509E8, 0x505E8, 0x218 },
    { func_80050C00, 0x50800, 0x390 },
    { func_80050F90, 0x50B90, 0x220 },
    { func_800511B0, 0x50DB0, 0x230 },
    { func_800513E0, 0x50FE0, 0x25C },
    { func_8005163C, 0x5123C, 0x19C },
    { func_800517D8, 0x513D8, 0xC0 },
    { func_80051898, 0x51498, 0x9C },
    { func_80051934, 0x51534, 0x94 },
    { func_800519C8, 0x515C8, 0x2C4 },
    { func_80051C8C, 0x5188C, 0x3D4 },
    { func_80052060, 0x51C60, 0x160 },
    { func_800521C0, 0x51DC0, 0x48 },
    { func_80052208, 0x51E08, 0x800 },
    { func_80052A08, 0x52608, 0x444 },
    { func_80052E4C, 0x52A4C, 0x280 },
    { func_800530CC, 0x52CCC, 0x15C },
    { func_80053228, 0x52E28, 0xD8 },
    { func_80053300, 0x52F00, 0x84 },
    { func_80053384, 0x52F84, 0x884 },
    { func_80053C08, 0x53808, 0x440 },
    { func_80054048, 0x53C48, 0x1AAC },
    { func_80055AF4, 0x556F4, 0x970 },
    { func_80056464, 0x56064, 0x1A70 },
    { func_80057ED4, 0x57AD4, 0x74 },
    { func_80057F48, 0x57B48, 0x1F0C },
    { func_80059E54, 0x59A54, 0x147C },
    { func_8005B2D0, 0x5AED0, 0x438 },
    { func_8005B708, 0x5B308, 0x5C },
    { func_8005B764, 0x5B364, 0xAC },
    { func_8005B810, 0x5B410, 0xA00 },
    { func_8005C210, 0x5BE10, 0xEFC },
    { func_8005D10C, 0x5CD0C, 0x218 },
    { func_8005D324, 0x5CF24, 0x888 },
    { func_8005DBAC, 0x5D7AC, 0x5F8 },
    { func_8005E1A4, 0x5DDA4, 0x868 },
    { func_8005EA0C, 0x5E60C, 0x64 },
    { func_8005EA70, 0x5E670, 0x50 },
    { func_8005EAC0, 0x5E6C0, 0x158 },
    { func_8005EC18, 0x5E818, 0x158 },
    { func_8005ED70, 0x5E970, 0xA8 },
    { func_8005EE18, 0x5EA18, 0xF0 },
    { func_8005EF08, 0x5EB08, 0x434 },
    { func_8005F33C, 0x5EF3C, 0x19C },
    { func_8005F4D8, 0x5F0D8, 0x470 },
    { func_8005F948, 0x5F548, 0x84 },
    { func_8005F9CC, 0x5F5CC, 0x6C },
    { func_8005FA38, 0x5F638, 0x5F8 },
    { func_80060030, 0x5FC30, 0x850 },
    { func_80060880, 0x60480, 0x3EC },
    { func_80060C6C, 0x6086C, 0x104 },
    { func_80060D70, 0x60970, 0x74 },
    { func_80060DE4, 0x609E4, 0x1490 },
    { func_80062274, 0x61E74, 0xA0C },
    { func_80062C80, 0x62880, 0x194 },
    { func_80062E14, 0x62A14, 0xB4 },
    { func_80062EC8, 0x62AC8, 0x1BC },
    { func_80063084, 0x62C84, 0x64C },
    { func_800636D0, 0x632D0, 0x78 },
    { func_80063748, 0x63348, 0x358 },
    { func_80063AA0, 0x636A0, 0x5C },
    { math_vector_func_80063AFC, 0x636FC, 0x64 },
    { func_80063B60, 0x63760, 0x2A8 },
    { func_80063E08, 0x63A08, 0x44 },
    { func_80063E4C, 0x63A4C, 0xAC },
    { func_80063EF8, 0x63AF8, 0xB50 },
    { func_80064A48, 0x64648, 0x108 },
    { func_80064B50, 0x64750, 0x340 },
    { func_80064E90, 0x64A90, 0x8C },
    { func_80064F1C, 0x64B1C, 0x774 },
    { func_80065690, 0x65290, 0x180 },
    { func_80065810, 0x65410, 0x440 },
    { func_80065C50, 0x65850, 0x24 },
    { func_80065C74, 0x65874, 0x5C },
    { func_80065CD0, 0x658D0, 0x184 },
    { func_80065E54, 0x65A54, 0x750 },
    { func_800665A4, 0x661A4, 0x4DC },
    { func_80066A80, 0x66680, 0x64C },
    { func_800670CC, 0x66CCC, 0x208 },
    { func_800672D4, 0x66ED4, 0x444 },
    { func_80067718, 0x67318, 0x190 },
    { func_800678A8, 0x674A8, 0x20C },
    { func_80067AB4, 0x676B4, 0x95C },
    { func_80068410, 0x68010, 0x590 },
    { func_800689A0, 0x685A0, 0x10C },
    { func_80068AAC, 0x686AC, 0x258 },
    { func_80068D04, 0x68904, 0x378 },
    { func_8006907C, 0x68C7C, 0x558 },
    { func_800695D4, 0x691D4, 0x490 },
    { func_80069A64, 0x69664, 0x45C },
    { func_80069EC0, 0x69AC0, 0x52C },
    { func_8006A3EC, 0x69FEC, 0x5E8 },
    { func_8006A9D4, 0x6A5D4, 0x204 },
    { func_8006ABD8, 0x6A7D8, 0x370 },
    { func_8006AF48, 0x6AB48, 0x3C0 },
    { func_8006B308, 0x6AF08, 0x260 },
    { func_8006B568, 0x6B168, 0x460 },
    { func_8006B9C8, 0x6B5C8, 0x188 },
    { func_8006BB50, 0x6B750, 0x584 },
    { func_8006C0D4, 0x6BCD4, 0x87C },
    { func_8006C950, 0x6C550, 0xDC },
    { func_8006CA2C, 0x6C62C, 0x724 },
    { func_8006D150, 0x6CD50, 0x6A4 },
    { func_8006D7F4, 0x6D3F4, 0x328 },
    { func_8006DB1C, 0x6D71C, 0x4EC },
    { func_8006E008, 0x6DC08, 0x2C },
    { func_8006E034, 0x6DC34, 0x1A0 },
    { func_8006E1D4, 0x6DDD4, 0x280 },
    { func_8006E454, 0x6E054, 0x2A4 },
    { func_8006E6F8, 0x6E2F8, 0x1310 },
    { func_8006FA08, 0x6F608, 0xF8 },
    { func_8006FB00, 0x6F700, 0x180 },
    { func_8006FC80, 0x6F880, 0x164 },
    { func_8006FDE4, 0x6F9E4, 0x5BC },
    { func_800703A0, 0x6FFA0, 0x108 },
    { func_800704A8, 0x700A8, 0x2BC },
    { func_80070764, 0x70364, 0x458 },
    { func_80070BBC, 0x707BC, 0xD20 },
    { func_800718DC, 0x714DC, 0x11F4 },
    { func_80072AD0, 0x726D0, 0x9A0 },
    { func_80073470, 0x73070, 0x14C },
    { func_800735BC, 0x731BC, 0x84 },
    { func_80073640, 0x73240, 0xD4 },
    { func_80073714, 0x73314, 0x1C0 },
    { func_800738D4, 0x734D4, 0x3FC },
    { func_80073CD0, 0x738D0, 0x7A4 },
    { func_80074474, 0x74074, 0x138 },
    { func_800745AC, 0x741AC, 0x238 },
    { func_800747E4, 0x743E4, 0x324 },
    { func_80074B08, 0x74708, 0x1D4 },
    { func_80074CDC, 0x748DC, 0x640 },
    { func_8007531C, 0x74F1C, 0x180 },
    { func_8007549C, 0x7509C, 0x160 },
    { func_800755FC, 0x751FC, 0x4C },
    { func_80075648, 0x75248, 0x300 },
    { func_80075948, 0x75548, 0xF4 },
    { func_80075A3C, 0x7563C, 0x16C },
    { func_80075BA8, 0x757A8, 0x41C },
    { func_80075FC4, 0x75BC4, 0x1BC },
    { func_80076180, 0x75D80, 0x1B14 },
    { func_80077C94, 0x77894, 0x1A80 },
    { func_80079714, 0x79314, 0x15D8 },
    { func_8007ACEC, 0x7A8EC, 0x2FC },
    { func_8007AFE8, 0x7ABE8, 0x84 },
    { func_8007B06C, 0x7AC6C, 0x1F0 },
    { func_8007B25C, 0x7AE5C, 0xF0 },
    { func_8007B34C, 0x7AF4C, 0xE4 },
    { func_8007B430, 0x7B030, 0x114 },
    { func_8007B544, 0x7B144, 0x188 },
    { func_8007B6CC, 0x7B2CC, 0x78 },
    { func_8007B744, 0x7B344, 0xE4 },
    { func_8007B828, 0x7B428, 0x1BC },
    { func_8007B9E4, 0x7B5E4, 0x14C },
    { func_8007BB30, 0x7B730, 0xBC },
    { func_8007BBEC, 0x7B7EC, 0x208 },
    { func_8007BDF4, 0x7B9F4, 0x74 },
    { func_8007BE68, 0x7BA68, 0x20C },
    { func_8007C074, 0x7BC74, 0x350 },
    { func_8007C3C4, 0x7BFC4, 0x104 },
    { func_8007C4C8, 0x7C0C8, 0x184 },
    { func_8007C64C, 0x7C24C, 0x1CC },
    { func_8007C818, 0x7C418, 0x430 },
    { func_8007CC48, 0x7C848, 0x6C8 },
    { func_8007D310, 0x7CF10, 0xBC },
    { func_8007D3CC, 0x7CFCC, 0x660 },
    { func_8007DA2C, 0x7D62C, 0x178 },
    { func_8007DBA4, 0x7D7A4, 0x334 },
    { func_8007DED8, 0x7DAD8, 0x1D4 },
    { func_8007E0AC, 0x7DCAC, 0x40 },
    { func_8007E0EC, 0x7DCEC, 0xA90 },
    { func_8007EB7C, 0x7E77C, 0x2D0 },
    { func_8007EE4C, 0x7EA4C, 0x24C },
    { func_8007F098, 0x7EC98, 0x1B4 },
    { func_8007F24C, 0x7EE4C, 0x1E4 },
    { func_8007F430, 0x7F030, 0x130 },
    { func_8007F560, 0x7F160, 0x83C },
    { func_8007FD9C, 0x7F99C, 0x24 },
    { func_8007FDC0, 0x7F9C0, 0x59C },
    { func_8008035C, 0x7FF5C, 0xAC },
    { func_80080408, 0x80008, 0x90 },
    { func_80080498, 0x80098, 0x348 },
    { func_800807E0, 0x803E0, 0x100 },
    { func_800808E0, 0x804E0, 0x13C },
    { func_80080A1C, 0x8061C, 0x1D0 },
    { func_80080BEC, 0x807EC, 0x5F0 },
    { func_800811DC, 0x80DDC, 0x90 },
    { func_8008126C, 0x80E6C, 0x8C },
    { func_800812F8, 0x80EF8, 0x70 },
    { func_80081368, 0x80F68, 0x4AC },
    { func_80081814, 0x81414, 0x134 },
    { func_80081948, 0x81548, 0xEC },
    { func_80081A34, 0x81634, 0x1B4 },
    { func_80081BE8, 0x817E8, 0x3C8 },
    { func_80081FB0, 0x81BB0, 0x490 },
    { func_80082440, 0x82040, 0x1E4 },
    { func_80082624, 0x82224, 0x1BC },
    { func_800827E0, 0x823E0, 0x214 },
    { func_800829F4, 0x825F4, 0x144 },
    { func_80082B38, 0x82738, 0xB0 },
    { func_80082BE8, 0x827E8, 0x98 },
    { func_80082C80, 0x82880, 0x324 },
    { func_80082FA4, 0x82BA4, 0x190 },
    { func_80083134, 0x82D34, 0x5C },
    { func_80083190, 0x82D90, 0x224 },
    { func_800833B4, 0x82FB4, 0x9CC },
    { func_80083D80, 0x83980, 0x17C },
    { func_80083EFC, 0x83AFC, 0x24C },
    { func_80084148, 0x83D48, 0x1DC },
    { func_80084324, 0x83F24, 0x1A4 },
    { func_800844C8, 0x840C8, 0x574 },
    { func_80084A3C, 0x8463C, 0x1A0 },
    { func_80084BDC, 0x847DC, 0xE8 },
    { func_80084CC4, 0x848C4, 0x8C },
    { func_80084D50, 0x84950, 0x1CC },
    { func_80084F1C, 0x84B1C, 0x3CC },
    { func_800852E8, 0x84EE8, 0x50C },
    { func_800857F4, 0x853F4, 0x558 },
    { func_80085D4C, 0x8594C, 0xDC },
    { func_80085E28, 0x85A28, 0x88 },
    { func_80085EB0, 0x85AB0, 0x100 },
    { func_80085FB0, 0x85BB0, 0x330 },
    { func_800862E0, 0x85EE0, 0x120 },
    { func_80086400, 0x86000, 0x1E8 },
    { func_800865E8, 0x861E8, 0x158 },
    { func_80086740, 0x86340, 0x1FC },
    { func_8008693C, 0x8653C, 0xE4 },
    { func_80086A20, 0x86620, 0x16C },
    { func_80086B8C, 0x8678C, 0x114 },
    { func_80086CA0, 0x868A0, 0x48 },
    { func_80086CE8, 0x868E8, 0x1CC },
    { func_80086EB4, 0x86AB4, 0x1E0 },
    { func_80087094, 0x86C94, 0x3C },
    { func_800870D0, 0x86CD0, 0xC8 },
    { func_80087198, 0x86D98, 0x5BC },
    { func_80087754, 0x87354, 0x58 },
    { func_800877AC, 0x873AC, 0x218 },
    { func_800879C4, 0x875C4, 0x2FC },
    { static_0_80087CC0, 0x878C0, 0xB0 },
    { func_80087D70, 0x87970, 0x110 },
    { func_80087E80, 0x87A80, 0x1FC },
    { func_8008807C, 0x87C7C, 0x3C },
    { func_800880B8, 0x87CB8, 0xA4 },
    { func_8008815C, 0x87D5C, 0x154 },
    { func_800882B0, 0x87EB0, 0xB0 },
    { func_80088360, 0x87F60, 0xF0 },
    { func_80088450, 0x88050, 0x38 },
    { func_80088488, 0x88088, 0xB0 },
    { func_80088538, 0x88138, 0x298 },
    { cache_writeback_800887D0, 0x883D0, 0x300 },
    { cache_inval_80088AD0, 0x886D0, 0x50 },
    { func_80088B20, 0x88720, 0x50 },
    { func_80088B70, 0x88770, 0x5D4 },
    { func_80089144, 0x88D44, 0x240 },
    { func_80089384, 0x88F84, 0x28C },
    { func_80089610, 0x89210, 0x60 },
    { func_80089670, 0x89270, 0x60 },
    { func_800896D0, 0x892D0, 0x60 },
    { func_80089730, 0x89330, 0x60 },
    { func_80089790, 0x89390, 0x70 },
    { func_80089800, 0x89400, 0x70 },
    { func_80089870, 0x89470, 0x178 },
    { func_800899E8, 0x895E8, 0xC8 },
    { func_80089AB0, 0x896B0, 0x100 },
    { func_80089BB0, 0x897B0, 0x94 },
    { func_80089C44, 0x89844, 0x8C },
    { func_80089CD0, 0x898D0, 0xC0 },
    { func_80089D90, 0x89990, 0xC0 },
    { func_80089E50, 0x89A50, 0x4A0 },
    { func_8008A2F0, 0x89EF0, 0x70 },
    { func_8008A360, 0x89F60, 0x50 },
    { func_8008A3B0, 0x89FB0, 0x248 },
    { func_8008A5F8, 0x8A1F8, 0x98 },
    { func_8008A690, 0x8A290, 0x24 },
    { dma_read_rom, 0x8A2B4, 0x5C },
    { func_8008A710, 0x8A310, 0x5C8 },
    { func_8008ACD8, 0x8A8D8, 0xD8 },
    { func_8008ADB0, 0x8A9B0, 0x80 },
    { func_8008AE30, 0x8AA30, 0x70 },
    { func_8008AEA0, 0x8AAA0, 0x11C },
    { func_8008AFBC, 0x8ABBC, 0x190 },
    { func_8008B14C, 0x8AD4C, 0x44 },
    { func_8008B190, 0x8AD90, 0x20 },
    { func_8008B1B0, 0x8ADB0, 0x168 },
    { func_8008B318, 0x8AF18, 0x10C },
    { func_8008B424, 0x8B024, 0x15C },
    { os_init_system, 0x8B180, 0x290 },
    { os_create_mesg_queues, 0x8B410, 0x150 },
    { os_create_threads, 0x8B560, 0x150 },
    { func_8008BAB0, 0x8B6B0, 0x180 },
    { func_8008BC30, 0x8B830, 0x190 },
    { func_8008BDC0, 0x8B9C0, 0x1F0 },
    { func_8008BFB0, 0x8BBB0, 0xE0 },
    { func_8008C090, 0x8BC90, 0x70 },
    { func_8008C100, 0x8BD00, 0x90 },
    { func_8008C190, 0x8BD90, 0xF0 },
    { func_8008C280, 0x8BE80, 0x110 },
    { func_8008C390, 0x8BF90, 0x1C0 },
    { osGetCount_8008C550, 0x8C150, 0x220 },
    { func_8008C770, 0x8C370, 0x40 },
    { func_8008C7B0, 0x8C3B0, 0x180 },
    { func_8008C930, 0x8C530, 0x198 },
    { func_8008CAC8, 0x8C6C8, 0x664 },
    { libultra_split_8008D12C, 0x8CD2C, 0x158 },
    { libultra_split_8008D284, 0x8CE84, 0x1A8 },
    { func_8008D42C, 0x8D02C, 0x24 },
    { libultra_split_8008D450, 0x8D050, 0xC0 },
    { func_8008D510, 0x8D110, 0x44 },
    { func_8008D554, 0x8D154, 0x54 },
    { func_8008D5A8, 0x8D1A8, 0x54 },
    { func_8008D5FC, 0x8D1FC, 0x88 },
    { func_8008D684, 0x8D284, 0xA8 },
    { func_8008D72C, 0x8D32C, 0x144 },
    { func_8008D870, 0x8D470, 0x440 },
    { func_8008DCB0, 0x8D8B0, 0xD0 },
    { func_8008DD80, 0x8D980, 0x120 },
    { func_8008DEA0, 0x8DAA0, 0x1D4 },
    { func_8008E074, 0x8DC74, 0x3AC },
    { func_8008E420, 0x8E020, 0x12C },
    { func_8008E54C, 0x8E14C, 0x4A8 },
    { func_8008E9F4, 0x8E5F4, 0xE8 },
    { func_8008EADC, 0x8E6DC, 0x328 },
    { func_8008EE04, 0x8EA04, 0xE0 },
    { func_8008EEE4, 0x8EAE4, 0x1D0 },
    { func_8008F0B4, 0x8ECB4, 0x348 },
    { func_8008F3FC, 0x8EFFC, 0x584 },
    { func_8008F980, 0x8F580, 0x114 },
    { func_8008FA94, 0x8F694, 0x8C },
    { func_8008FB20, 0x8F720, 0xAC },
    { func_8008FBCC, 0x8F7CC, 0x70 },
    { func_8008FC3C, 0x8F83C, 0x124 },
    { func_8008FD60, 0x8F960, 0x8C },
    { func_8008FDEC, 0x8F9EC, 0x74 },
    { func_8008FE60, 0x8FA60, 0x50 },
    { func_8008FEB0, 0x8FAB0, 0xE8 },
    { func_8008FF98, 0x8FB98, 0x148 },
    { func_800900E0, 0x8FCE0, 0x90 },
    { func_80090170, 0x8FD70, 0x90 },
    { func_80090200, 0x8FE00, 0xA0 },
    { func_800902A0, 0x8FEA0, 0x90 },
    { func_80090330, 0x8FF30, 0xA0 },
    { func_800903D0, 0x8FFD0, 0x80 },
    { func_80090450, 0x90050, 0x150 },
    { func_800905A0, 0x901A0, 0x58 },
    { func_800905F8, 0x901F8, 0x3C },
    { func_80090634, 0x90234, 0x2C },
    { func_80090660, 0x90260, 0x90 },
    { func_800906F0, 0x902F0, 0xE0 },
    { osSi_func, 0x903D0, 0xB0 },
    { func_80090880, 0x90480, 0xE0 },
    { func_80090960, 0x90560, 0xB0 },
    { func_80090A10, 0x90610, 0x210 },
    { func_80090C20, 0x90820, 0x350 },
    { func_80090F70, 0x90B70, 0x164 },
    { func_800910D4, 0x90CD4, 0x1AC },
    { func_80091280, 0x90E80, 0xD4 },
    { func_80091354, 0x90F54, 0xAE0 },
    { func_80091E34, 0x91A34, 0x19C },
    { func_80091FD0, 0x91BD0, 0x80 },
    { func_80092050, 0x91C50, 0x510 },
    { func_80092560, 0x92160, 0x140 },
    { func_800926A0, 0x922A0, 0x250 },
    { func_800928F0, 0x924F0, 0x220 },
    { func_80092B10, 0x92710, 0x670 },
    { func_80093180, 0x92D80, 0x650 },
    { pi_create_access_queue, 0x933D0, 0x58 },
    { pi_rel_access, 0x93428, 0x3C },
    { pi_read_io, 0x93464, 0x34 },
    { osWritebackDCache_80093898, 0x93498, 0x68 },
    { libultra_split_80093900, 0x93500, 0x98 },
    { osSp_small, 0x93598, 0x38 },
    { osSpTask_candidate, 0x935D0, 0x98 },
    { func_80093A68, 0x93668, 0x1C8 },
    { os_set_cause, 0x93830, 0x50 },
    { __osSetCompare_80093C80, 0x93880, 0x50 },
    { libultra_split_80093CD0, 0x938D0, 0x80 },
    { libultra_split_80093D50, 0x93950, 0xF4 },
    { func_80093E44, 0x93A44, 0x170 },
    { func_80093FB4, 0x93BB4, 0x74 },
    { func_80094028, 0x93C28, 0x1B8 },
    { osViManager_candidate, 0x93DE0, 0x300 },
    { osPiStartDma_candidate_800944E0, 0x940E0, 0xE0 },
    { osPiManager_candidate_800945C0, 0x941C0, 0x230 },
    { func_800947F0, 0x943F0, 0x490 },
    { func_80094C80, 0x94880, 0x1C4 },
    { func_80094E44, 0x94A44, 0x8C },
    { func_80094ED0, 0x94AD0, 0x178 },
    { func_80095048, 0x94C48, 0xAC },
    { func_800950F4, 0x94CF4, 0x1B8 },
    { osPiManager_candidate_800952AC, 0x94EAC, 0x574 },
    { osPiStartDma_candidate_80095820, 0x95420, 0xBC },
    { func_800958DC, 0x954DC, 0xB4 },
    { func_80095990, 0x95590, 0x1D8 },
    { func_80095B68, 0x95768, 0xB8 },
    { func_80095C20, 0x95820, 0x188 },
    { func_80095DA8, 0x959A8, 0x18C },
    { func_80095F34, 0x95B34, 0x228 },
    { func_8009615C, 0x95D5C, 0x270 },
    { func_800963CC, 0x95FCC, 0x3C4 },
    { func_80096790, 0x96390, 0x1A0 },
    { func_80096930, 0x96530, 0xD8 },
    { func_80096A08, 0x96608, 0x1E8 },
    { func_80096BF0, 0x967F0, 0x2A0 },
    { func_80096E90, 0x96A90, 0x570 },
    { func_80097400, 0x97000, 0x558 },
    { osPiRaw_io, 0x97558, 0x38 },
    { pi_raw_start_dma, 0x97590, 0x68 },
    { osPiManager_candidate_800979F8, 0x975F8, 0x190 },
    { osPiManager_candidate_80097B88, 0x97788, 0x198 },
    { func_80097D20, 0x97920, 0x50 },
    { func_80097D70, 0x97970, 0x50 },
    { func_80097DC0, 0x979C0, 0xA0 },
    { func_80097E60, 0x97A60, 0x108 },
    { func_80097F68, 0x97B68, 0x498 },
    { static_0_8000097C, 0x57C, 0x0 },  // auto-detected
    { static_0_80002BD4, 0x27D4, 0x0 },  // auto-detected
    { static_0_80002E2C, 0x2A2C, 0x0 },  // auto-detected
    { static_0_80004000, 0x3C00, 0x0 },  // auto-detected
    { static_0_80004160, 0x3D60, 0x0 },  // auto-detected
    { static_0_8000550C, 0x510C, 0x0 },  // auto-detected
    { static_0_8000556C, 0x516C, 0x0 },  // auto-detected
    { static_0_800059A8, 0x55A8, 0x0 },  // auto-detected
    { static_0_80005AFC, 0x56FC, 0x0 },  // auto-detected
    { static_0_80005B1C, 0x571C, 0x0 },  // auto-detected
    { static_0_80005B44, 0x5744, 0x0 },  // auto-detected
    { static_0_80005B80, 0x5780, 0x0 },  // auto-detected
    { static_0_80005BB8, 0x57B8, 0x0 },  // auto-detected
    { static_0_80005CAC, 0x58AC, 0x0 },  // auto-detected
    { static_0_8000630C, 0x5F0C, 0x0 },  // auto-detected
    { static_0_80006704, 0x6304, 0x0 },  // auto-detected
    { static_0_80006DE8, 0x69E8, 0x0 },  // auto-detected
    { static_0_80006E50, 0x6A50, 0x0 },  // auto-detected
    { static_0_80006E60, 0x6A60, 0x0 },  // auto-detected
    { static_0_80006E74, 0x6A74, 0x0 },  // auto-detected
    { static_0_80006EB4, 0x6AB4, 0x0 },  // auto-detected
    { static_0_80006F28, 0x6B28, 0x0 },  // auto-detected
    { static_0_80006FD4, 0x6BD4, 0x0 },  // auto-detected
    { static_0_80006FDC, 0x6BDC, 0x0 },  // auto-detected
    { static_0_800073A4, 0x6FA4, 0x0 },  // auto-detected
    { static_0_8000787C, 0x747C, 0x0 },  // auto-detected
    { static_0_80007A44, 0x7644, 0x0 },  // auto-detected
    { static_0_80007A80, 0x7680, 0x0 },  // auto-detected
    { static_0_80007B10, 0x7710, 0x0 },  // auto-detected
    { static_0_80007CE4, 0x78E4, 0x0 },  // auto-detected
    { static_0_8000803C, 0x7C3C, 0x0 },  // auto-detected
    { static_0_80008530, 0x8130, 0x0 },  // auto-detected
    { static_0_80008540, 0x8140, 0x0 },  // auto-detected
    { static_0_80008548, 0x8148, 0x0 },  // auto-detected
    { static_0_80008718, 0x8318, 0x0 },  // auto-detected
    { static_0_80008750, 0x8350, 0x0 },  // auto-detected
    { static_0_80008B14, 0x8714, 0x0 },  // auto-detected
    { static_0_80008B68, 0x8768, 0x0 },  // auto-detected
    { static_0_80008F28, 0x8B28, 0x0 },  // auto-detected
    { static_0_80008F58, 0x8B58, 0x0 },  // auto-detected
    { static_0_80008F6C, 0x8B6C, 0x0 },  // auto-detected
    { static_0_80009134, 0x8D34, 0x0 },  // auto-detected
    { static_0_80009278, 0x8E78, 0x0 },  // auto-detected
    { static_0_800092B0, 0x8EB0, 0x0 },  // auto-detected
    { static_0_80009524, 0x9124, 0x0 },  // auto-detected
    { static_0_8000953C, 0x913C, 0x0 },  // auto-detected
    { static_0_8000955C, 0x915C, 0x0 },  // auto-detected
    { static_0_80009820, 0x9420, 0x0 },  // auto-detected
    { static_0_80009FA0, 0x9BA0, 0x0 },  // auto-detected
    { static_0_8000A44C, 0xA04C, 0x0 },  // auto-detected
    { static_0_8000A920, 0xA520, 0x0 },  // auto-detected
    { static_0_8000AA04, 0xA604, 0x0 },  // auto-detected
    { static_0_8000AA78, 0xA678, 0x0 },  // auto-detected
    { static_0_8000AAC0, 0xA6C0, 0x0 },  // auto-detected
    { static_0_8000AAF8, 0xA6F8, 0x0 },  // auto-detected
    { static_0_8000AB24, 0xA724, 0x0 },  // auto-detected
    { static_0_8000ABD4, 0xA7D4, 0x0 },  // auto-detected
    { static_0_8000AC34, 0xA834, 0x0 },  // auto-detected
    { static_0_8000AC60, 0xA860, 0x0 },  // auto-detected
    { static_0_8000ACC0, 0xA8C0, 0x0 },  // auto-detected
    { static_0_8000AED4, 0xAAD4, 0x0 },  // auto-detected
    { static_0_8000AEFC, 0xAAFC, 0x0 },  // auto-detected
    { static_0_8000AF4C, 0xAB4C, 0x0 },  // auto-detected
    { static_0_8000B02C, 0xAC2C, 0x0 },  // auto-detected
    { static_0_8000B1B0, 0xADB0, 0x0 },  // auto-detected
    { static_0_8000B318, 0xAF18, 0x0 },  // auto-detected
    { static_0_8000BC10, 0xB810, 0x0 },  // auto-detected
    { static_0_8000C530, 0xC130, 0x0 },  // auto-detected
    { static_0_8000C5F0, 0xC1F0, 0x0 },  // auto-detected
    { static_0_8000C658, 0xC258, 0x0 },  // auto-detected
    { static_0_8000C6C8, 0xC2C8, 0x0 },  // auto-detected
    { static_0_8000C724, 0xC324, 0x0 },  // auto-detected
    { static_0_8000D89C, 0xD49C, 0x0 },  // auto-detected
    { static_0_8000D90C, 0xD50C, 0x0 },  // auto-detected
    { static_0_8000D960, 0xD560, 0x0 },  // auto-detected
    { static_0_8000D9A8, 0xD5A8, 0x0 },  // auto-detected
    { static_0_8000DA6C, 0xD66C, 0x0 },  // auto-detected
    { static_0_8000DA78, 0xD678, 0x0 },  // auto-detected
    { static_0_8000E680, 0xE280, 0x0 },  // auto-detected
    { static_0_8000E738, 0xE338, 0x0 },  // auto-detected
    { static_0_8000E9BC, 0xE5BC, 0x0 },  // auto-detected
    { static_0_8000EEE0, 0xEAE0, 0x0 },  // auto-detected
    { static_0_8000F5A0, 0xF1A0, 0x0 },  // auto-detected
    { static_0_8000FCA4, 0xF8A4, 0x0 },  // auto-detected
    { static_0_8000FCBC, 0xF8BC, 0x0 },  // auto-detected
    { static_0_8000FD74, 0xF974, 0x0 },  // auto-detected
    { static_0_8000FE1C, 0xFA1C, 0x0 },  // auto-detected
    { static_0_8000FE78, 0xFA78, 0x0 },  // auto-detected
    { static_0_8000FEAC, 0xFAAC, 0x0 },  // auto-detected
    { static_0_8000FEF0, 0xFAF0, 0x0 },  // auto-detected
    { static_0_8000FF54, 0xFB54, 0x0 },  // auto-detected
    { static_0_80010014, 0xFC14, 0x0 },  // auto-detected
    { static_0_80010040, 0xFC40, 0x0 },  // auto-detected
    { static_0_8001004C, 0xFC4C, 0x0 },  // auto-detected
    { static_0_80011764, 0x11364, 0x0 },  // auto-detected
    { static_0_80011778, 0x11378, 0x0 },  // auto-detected
    { static_0_800117E4, 0x113E4, 0x0 },  // auto-detected
    { static_0_80011814, 0x11414, 0x0 },  // auto-detected
    { static_0_80011824, 0x11424, 0x0 },  // auto-detected
    { static_0_80011838, 0x11438, 0x0 },  // auto-detected
    { static_0_80011888, 0x11488, 0x0 },  // auto-detected
    { static_0_80011918, 0x11518, 0x0 },  // auto-detected
    { static_0_80011928, 0x11528, 0x0 },  // auto-detected
    { static_0_80011DF0, 0x119F0, 0x0 },  // auto-detected
    { static_0_80011E54, 0x11A54, 0x0 },  // auto-detected
    { static_0_80011ECC, 0x11ACC, 0x0 },  // auto-detected
    { static_0_80011EE8, 0x11AE8, 0x0 },  // auto-detected
    { static_0_80011F04, 0x11B04, 0x0 },  // auto-detected
    { static_0_80011F38, 0x11B38, 0x0 },  // auto-detected
    { static_0_800129B8, 0x125B8, 0x0 },  // auto-detected
    { static_0_800141EC, 0x13DEC, 0x0 },  // auto-detected
    { static_0_80014C98, 0x14898, 0x0 },  // auto-detected
    { static_0_80014CC0, 0x148C0, 0x0 },  // auto-detected
    { static_0_80014D4C, 0x1494C, 0x0 },  // auto-detected
    { static_0_80014F54, 0x14B54, 0x0 },  // auto-detected
    { static_0_8001514C, 0x14D4C, 0x0 },  // auto-detected
    { static_0_80015170, 0x14D70, 0x0 },  // auto-detected
    { static_0_80015190, 0x14D90, 0x0 },  // auto-detected
    { static_0_800151C0, 0x14DC0, 0x0 },  // auto-detected
    { static_0_80015268, 0x14E68, 0x0 },  // auto-detected
    { static_0_80015288, 0x14E88, 0x0 },  // auto-detected
    { static_0_800152CC, 0x14ECC, 0x0 },  // auto-detected
    { static_0_80015328, 0x14F28, 0x0 },  // auto-detected
    { static_0_8001535C, 0x14F5C, 0x0 },  // auto-detected
    { static_0_80015390, 0x14F90, 0x0 },  // auto-detected
    { static_0_800153C0, 0x14FC0, 0x0 },  // auto-detected
    { static_0_800153EC, 0x14FEC, 0x0 },  // auto-detected
    { static_0_80015470, 0x15070, 0x0 },  // auto-detected
    { static_0_80015538, 0x15138, 0x0 },  // auto-detected
    { static_0_800155C0, 0x151C0, 0x0 },  // auto-detected
    { static_0_800155EC, 0x151EC, 0x0 },  // auto-detected
    { static_0_80015630, 0x15230, 0x0 },  // auto-detected
    { static_0_80015694, 0x15294, 0x0 },  // auto-detected
    { static_0_800156B8, 0x152B8, 0x0 },  // auto-detected
    { static_0_800156DC, 0x152DC, 0x0 },  // auto-detected
    { static_0_80015724, 0x15324, 0x0 },  // auto-detected
    { static_0_80015C30, 0x15830, 0x0 },  // auto-detected
    { static_0_800160BC, 0x15CBC, 0x0 },  // auto-detected
    { static_0_80016BF4, 0x167F4, 0x0 },  // auto-detected
    { static_0_80016CAC, 0x168AC, 0x0 },  // auto-detected
    { static_0_80016D78, 0x16978, 0x0 },  // auto-detected
    { static_0_80016DD8, 0x169D8, 0x0 },  // auto-detected
    { static_0_80017520, 0x17120, 0x0 },  // auto-detected
    { static_0_80017580, 0x17180, 0x0 },  // auto-detected
    { static_0_80017874, 0x17474, 0x0 },  // auto-detected
    { static_0_80017918, 0x17518, 0x0 },  // auto-detected
    { static_0_80017B34, 0x17734, 0x0 },  // auto-detected
    { static_0_80017B7C, 0x1777C, 0x0 },  // auto-detected
    { static_0_80017BA8, 0x177A8, 0x0 },  // auto-detected
    { static_0_80017C18, 0x17818, 0x0 },  // auto-detected
    { static_0_80017C98, 0x17898, 0x0 },  // auto-detected
    { static_0_80017D48, 0x17948, 0x0 },  // auto-detected
    { static_0_80017D58, 0x17958, 0x0 },  // auto-detected
    { static_0_80017DA4, 0x179A4, 0x0 },  // auto-detected
    { static_0_80017DAC, 0x179AC, 0x0 },  // auto-detected
    { static_0_80017DB4, 0x179B4, 0x0 },  // auto-detected
    { static_0_80017DDC, 0x179DC, 0x0 },  // auto-detected
    { static_0_80017DE4, 0x179E4, 0x0 },  // auto-detected
    { static_0_80017DEC, 0x179EC, 0x0 },  // auto-detected
    { static_0_80017DF4, 0x179F4, 0x0 },  // auto-detected
    { static_0_80017E20, 0x17A20, 0x0 },  // auto-detected
    { static_0_80017E54, 0x17A54, 0x0 },  // auto-detected
    { static_0_80017E5C, 0x17A5C, 0x0 },  // auto-detected
    { static_0_80017E70, 0x17A70, 0x0 },  // auto-detected
    { static_0_80017E88, 0x17A88, 0x0 },  // auto-detected
    { static_0_80017EDC, 0x17ADC, 0x0 },  // auto-detected
    { static_0_80017EE4, 0x17AE4, 0x0 },  // auto-detected
    { static_0_80017EEC, 0x17AEC, 0x0 },  // auto-detected
    { static_0_80017EF4, 0x17AF4, 0x0 },  // auto-detected
    { static_0_80017F20, 0x17B20, 0x0 },  // auto-detected
    { static_0_80017F28, 0x17B28, 0x0 },  // auto-detected
    { static_0_80018114, 0x17D14, 0x0 },  // auto-detected
    { static_0_8001811C, 0x17D1C, 0x0 },  // auto-detected
    { static_0_800182FC, 0x17EFC, 0x0 },  // auto-detected
    { static_0_80018324, 0x17F24, 0x0 },  // auto-detected
    { static_0_800183A8, 0x17FA8, 0x0 },  // auto-detected
    { static_0_800183B0, 0x17FB0, 0x0 },  // auto-detected
    { static_0_800183C0, 0x17FC0, 0x0 },  // auto-detected
    { static_0_80018440, 0x18040, 0x0 },  // auto-detected
    { static_0_80018448, 0x18048, 0x0 },  // auto-detected
    { static_0_80018450, 0x18050, 0x0 },  // auto-detected
    { static_0_80018470, 0x18070, 0x0 },  // auto-detected
    { static_0_80018480, 0x18080, 0x0 },  // auto-detected
    { static_0_80019BB4, 0x197B4, 0x0 },  // auto-detected
    { static_0_8001A408, 0x1A008, 0x0 },  // auto-detected
    { static_0_8001ADD4, 0x1A9D4, 0x0 },  // auto-detected
    { static_0_8001CCC4, 0x1C8C4, 0x0 },  // auto-detected
    { static_0_8001D05C, 0x1CC5C, 0x0 },  // auto-detected
    { static_0_8001DD48, 0x1D948, 0x0 },  // auto-detected
    { static_0_8001E6C0, 0x1E2C0, 0x0 },  // auto-detected
    { static_0_8001F464, 0x1F064, 0x0 },  // auto-detected
    { static_0_8001F5AC, 0x1F1AC, 0x0 },  // auto-detected
    { static_0_80020030, 0x1FC30, 0x0 },  // auto-detected
    { static_0_80021F84, 0x21B84, 0x0 },  // auto-detected
    { static_0_800228C0, 0x224C0, 0x0 },  // auto-detected
    { static_0_80024070, 0x23C70, 0x0 },  // auto-detected
    { static_0_80024704, 0x24304, 0x0 },  // auto-detected
    { static_0_80024954, 0x24554, 0x0 },  // auto-detected
    { static_0_80026644, 0x26244, 0x0 },  // auto-detected
    { static_0_80027A0C, 0x2760C, 0x0 },  // auto-detected
    { static_0_80027D24, 0x27924, 0x0 },  // auto-detected
    { static_0_800281F0, 0x27DF0, 0x0 },  // auto-detected
    { static_0_80028E78, 0x28A78, 0x0 },  // auto-detected
    { static_0_800290A4, 0x28CA4, 0x0 },  // auto-detected
    { static_0_80029298, 0x28E98, 0x0 },  // auto-detected
    { static_0_8002932C, 0x28F2C, 0x0 },  // auto-detected
    { static_0_80029494, 0x29094, 0x0 },  // auto-detected
    { static_0_80029A3C, 0x2963C, 0x0 },  // auto-detected
    { static_0_80029C24, 0x29824, 0x0 },  // auto-detected
    { static_0_8002A7D4, 0x2A3D4, 0x0 },  // auto-detected
    { static_0_8002B3C8, 0x2AFC8, 0x0 },  // auto-detected
    { static_0_8002C780, 0x2C380, 0x0 },  // auto-detected
    { static_0_8002CC28, 0x2C828, 0x0 },  // auto-detected
    { static_0_8002D4C4, 0x2D0C4, 0x0 },  // auto-detected
    { static_0_8002D598, 0x2D198, 0x0 },  // auto-detected
    { static_0_8002D6EC, 0x2D2EC, 0x0 },  // auto-detected
    { static_0_8002D968, 0x2D568, 0x0 },  // auto-detected
    { static_0_8002D9D0, 0x2D5D0, 0x0 },  // auto-detected
    { static_0_8002DA0C, 0x2D60C, 0x0 },  // auto-detected
    { static_0_8002DAD0, 0x2D6D0, 0x0 },  // auto-detected
    { static_0_8002DC7C, 0x2D87C, 0x0 },  // auto-detected
    { static_0_8002DFB0, 0x2DBB0, 0x0 },  // auto-detected
    { static_0_8002E028, 0x2DC28, 0x0 },  // auto-detected
    { static_0_8002E0A8, 0x2DCA8, 0x0 },  // auto-detected
    { static_0_8002E0B4, 0x2DCB4, 0x0 },  // auto-detected
    { static_0_8002E124, 0x2DD24, 0x0 },  // auto-detected
    { static_0_8002E6E0, 0x2E2E0, 0x0 },  // auto-detected
    { static_0_8002E8D4, 0x2E4D4, 0x0 },  // auto-detected
    { static_0_8002EA28, 0x2E628, 0x0 },  // auto-detected
    { static_0_8002F024, 0x2EC24, 0x0 },  // auto-detected
    { static_0_8002F054, 0x2EC54, 0x0 },  // auto-detected
    { static_0_8002F060, 0x2EC60, 0x0 },  // auto-detected
    { static_0_8002F06C, 0x2EC6C, 0x0 },  // auto-detected
    { static_0_8002F0EC, 0x2ECEC, 0x0 },  // auto-detected
    { static_0_8002F144, 0x2ED44, 0x0 },  // auto-detected
    { static_0_8002F1CC, 0x2EDCC, 0x0 },  // auto-detected
    { static_0_8002F1E4, 0x2EDE4, 0x0 },  // auto-detected
    { static_0_8002F1EC, 0x2EDEC, 0x0 },  // auto-detected
    { static_0_8002F2D0, 0x2EED0, 0x0 },  // auto-detected
    { static_0_8002FA00, 0x2F600, 0x0 },  // auto-detected
    { static_0_8002FAC4, 0x2F6C4, 0x0 },  // auto-detected
    { static_0_8002FAFC, 0x2F6FC, 0x0 },  // auto-detected
    { static_0_8002FC80, 0x2F880, 0x0 },  // auto-detected
    { static_0_8002FDF8, 0x2F9F8, 0x0 },  // auto-detected
    { static_0_80030574, 0x30174, 0x0 },  // auto-detected
    { static_0_800305E8, 0x301E8, 0x0 },  // auto-detected
    { static_0_80030A7C, 0x3067C, 0x0 },  // auto-detected
    { static_0_80030B68, 0x30768, 0x0 },  // auto-detected
    { static_0_80030C98, 0x30898, 0x0 },  // auto-detected
    { static_0_80030EA0, 0x30AA0, 0x0 },  // auto-detected
    { static_0_80030FF8, 0x30BF8, 0x0 },  // auto-detected
    { static_0_800313D8, 0x30FD8, 0x0 },  // auto-detected
    { static_0_800314DC, 0x310DC, 0x0 },  // auto-detected
    { static_0_80031944, 0x31544, 0x0 },  // auto-detected
    { static_0_80031BEC, 0x317EC, 0x0 },  // auto-detected
    { static_0_80031F94, 0x31B94, 0x0 },  // auto-detected
    { static_0_80031FA4, 0x31BA4, 0x0 },  // auto-detected
    { static_0_800320E0, 0x31CE0, 0x0 },  // auto-detected
    { static_0_800321F0, 0x31DF0, 0x0 },  // auto-detected
    { static_0_80033328, 0x32F28, 0x0 },  // auto-detected
    { static_0_800334F4, 0x330F4, 0x0 },  // auto-detected
    { static_0_80033B94, 0x33794, 0x0 },  // auto-detected
    { static_0_80033C70, 0x33870, 0x0 },  // auto-detected
    { static_0_80033D30, 0x33930, 0x0 },  // auto-detected
    { static_0_80033DC4, 0x339C4, 0x0 },  // auto-detected
    { static_0_80033DD0, 0x339D0, 0x0 },  // auto-detected
    { static_0_80033E08, 0x33A08, 0x0 },  // auto-detected
    { static_0_80033E40, 0x33A40, 0x0 },  // auto-detected
    { static_0_80033EEC, 0x33AEC, 0x0 },  // auto-detected
    { static_0_80033F94, 0x33B94, 0x0 },  // auto-detected
    { static_0_8003423C, 0x33E3C, 0x0 },  // auto-detected
    { static_0_80034374, 0x33F74, 0x0 },  // auto-detected
    { static_0_800344C8, 0x340C8, 0x0 },  // auto-detected
    { static_0_8003483C, 0x3443C, 0x0 },  // auto-detected
    { static_0_80034948, 0x34548, 0x0 },  // auto-detected
    { static_0_800349C4, 0x345C4, 0x0 },  // auto-detected
    { static_0_80034DA8, 0x349A8, 0x0 },  // auto-detected
    { static_0_80034E20, 0x34A20, 0x0 },  // auto-detected
    { static_0_8003527C, 0x34E7C, 0x0 },  // auto-detected
    { static_0_800352E4, 0x34EE4, 0x0 },  // auto-detected
    { static_0_80035698, 0x35298, 0x0 },  // auto-detected
    { static_0_800356BC, 0x352BC, 0x0 },  // auto-detected
    { static_0_800358A0, 0x354A0, 0x0 },  // auto-detected
    { static_0_8003594C, 0x3554C, 0x0 },  // auto-detected
    { static_0_8003609C, 0x35C9C, 0x0 },  // auto-detected
    { static_0_800366DC, 0x362DC, 0x0 },  // auto-detected
    { static_0_80036F7C, 0x36B7C, 0x0 },  // auto-detected
    { static_0_80037BF8, 0x377F8, 0x0 },  // auto-detected
    { static_0_80038C3C, 0x3883C, 0x0 },  // auto-detected
    { static_0_80038DBC, 0x389BC, 0x0 },  // auto-detected
    { static_0_80038DF8, 0x389F8, 0x0 },  // auto-detected
    { static_0_80038E58, 0x38A58, 0x0 },  // auto-detected
    { static_0_80038ED0, 0x38AD0, 0x0 },  // auto-detected
    { static_0_80038F68, 0x38B68, 0x0 },  // auto-detected
    { static_0_80038FE8, 0x38BE8, 0x0 },  // auto-detected
    { static_0_800390A4, 0x38CA4, 0x0 },  // auto-detected
    { static_0_800390AC, 0x38CAC, 0x0 },  // auto-detected
    { static_0_800390C0, 0x38CC0, 0x0 },  // auto-detected
    { static_0_80039178, 0x38D78, 0x0 },  // auto-detected
    { static_0_800392A4, 0x38EA4, 0x0 },  // auto-detected
    { static_0_8003960C, 0x3920C, 0x0 },  // auto-detected
    { static_0_800398B8, 0x394B8, 0x0 },  // auto-detected
    { static_0_80039914, 0x39514, 0x0 },  // auto-detected
    { static_0_80039984, 0x39584, 0x0 },  // auto-detected
    { static_0_800399F0, 0x395F0, 0x0 },  // auto-detected
    { static_0_80039A30, 0x39630, 0x0 },  // auto-detected
    { static_0_80039CD8, 0x398D8, 0x0 },  // auto-detected
    { static_0_8003A4A0, 0x3A0A0, 0x0 },  // auto-detected
    { static_0_8003A50C, 0x3A10C, 0x0 },  // auto-detected
    { static_0_8003A568, 0x3A168, 0x0 },  // auto-detected
    { static_0_8003A5D0, 0x3A1D0, 0x0 },  // auto-detected
    { static_0_8003B250, 0x3AE50, 0x0 },  // auto-detected
    { static_0_8003B300, 0x3AF00, 0x0 },  // auto-detected
    { static_0_8003B860, 0x3B460, 0x0 },  // auto-detected
    { static_0_8003BAB0, 0x3B6B0, 0x0 },  // auto-detected
    { static_0_8003D110, 0x3CD10, 0x0 },  // auto-detected
    { static_0_8003D370, 0x3CF70, 0x0 },  // auto-detected
    { static_0_8003D488, 0x3D088, 0x0 },  // auto-detected
    { static_0_8003D49C, 0x3D09C, 0x0 },  // auto-detected
    { static_0_8003D4F4, 0x3D0F4, 0x0 },  // auto-detected
    { static_0_8003E0A0, 0x3DCA0, 0x0 },  // auto-detected
    { static_0_8003E1D0, 0x3DDD0, 0x0 },  // auto-detected
    { static_0_8003E2B0, 0x3DEB0, 0x0 },  // auto-detected
    { static_0_8003E54C, 0x3E14C, 0x0 },  // auto-detected
    { static_0_8003E9D0, 0x3E5D0, 0x0 },  // auto-detected
    { static_0_8003EA24, 0x3E624, 0x0 },  // auto-detected
    { static_0_8003F084, 0x3EC84, 0x0 },  // auto-detected
    { static_0_8003F1C0, 0x3EDC0, 0x0 },  // auto-detected
    { static_0_8003F300, 0x3EF00, 0x0 },  // auto-detected
    { static_0_8003F714, 0x3F314, 0x0 },  // auto-detected
    { static_0_8003F7B8, 0x3F3B8, 0x0 },  // auto-detected
    { static_0_8003F800, 0x3F400, 0x0 },  // auto-detected
    { static_0_8003FB78, 0x3F778, 0x0 },  // auto-detected
    { static_0_8003FBD4, 0x3F7D4, 0x0 },  // auto-detected
    { static_0_80040050, 0x3FC50, 0x0 },  // auto-detected
    { static_0_8004110C, 0x40D0C, 0x0 },  // auto-detected
    { static_0_80041258, 0x40E58, 0x0 },  // auto-detected
    { static_0_800419B4, 0x415B4, 0x0 },  // auto-detected
    { static_0_80041F40, 0x41B40, 0x0 },  // auto-detected
    { static_0_80042970, 0x42570, 0x0 },  // auto-detected
    { static_0_80042EEC, 0x42AEC, 0x0 },  // auto-detected
    { static_0_80044A7C, 0x4467C, 0x0 },  // auto-detected
    { static_0_80044CD8, 0x448D8, 0x0 },  // auto-detected
    { static_0_800454A8, 0x450A8, 0x0 },  // auto-detected
    { static_0_80045634, 0x45234, 0x0 },  // auto-detected
    { static_0_80045694, 0x45294, 0x0 },  // auto-detected
    { static_0_80046764, 0x46364, 0x0 },  // auto-detected
    { static_0_800469B4, 0x465B4, 0x0 },  // auto-detected
    { static_0_80047920, 0x47520, 0x0 },  // auto-detected
    { static_0_800479A4, 0x475A4, 0x0 },  // auto-detected
    { static_0_80047DB0, 0x479B0, 0x0 },  // auto-detected
    { static_0_8004850C, 0x4810C, 0x0 },  // auto-detected
    { static_0_80048A50, 0x48650, 0x0 },  // auto-detected
    { static_0_8004DFEC, 0x4DBEC, 0x0 },  // auto-detected
    { static_0_8004E488, 0x4E088, 0x0 },  // auto-detected
    { static_0_8004F6E8, 0x4F2E8, 0x0 },  // auto-detected
    { static_0_8004FE30, 0x4FA30, 0x0 },  // auto-detected
    { static_0_8004FF7C, 0x4FB7C, 0x0 },  // auto-detected
    { static_0_80050208, 0x4FE08, 0x0 },  // auto-detected
    { static_0_80050F88, 0x50B88, 0x0 },  // auto-detected
    { static_0_80051994, 0x51594, 0x0 },  // auto-detected
    { static_0_800519C0, 0x515C0, 0x0 },  // auto-detected
    { static_0_80051C80, 0x51880, 0x0 },  // auto-detected
    { static_0_80051D2C, 0x5192C, 0x0 },  // auto-detected
    { static_0_80051FF4, 0x51BF4, 0x0 },  // auto-detected
    { static_0_800520C8, 0x51CC8, 0x0 },  // auto-detected
    { static_0_80052134, 0x51D34, 0x0 },  // auto-detected
    { static_0_80052E44, 0x52A44, 0x0 },  // auto-detected
    { static_0_80053220, 0x52E20, 0x0 },  // auto-detected
    { static_0_80053AD4, 0x536D4, 0x0 },  // auto-detected
    { static_0_800547EC, 0x543EC, 0x0 },  // auto-detected
    { static_0_80055AEC, 0x556EC, 0x0 },  // auto-detected
    { static_0_80055D38, 0x55938, 0x0 },  // auto-detected
    { static_0_80056844, 0x56444, 0x0 },  // auto-detected
    { static_0_800573E8, 0x56FE8, 0x0 },  // auto-detected
    { static_0_80058058, 0x57C58, 0x0 },  // auto-detected
    { static_0_8005B3F0, 0x5AFF0, 0x0 },  // auto-detected
    { static_0_8005C36C, 0x5BF6C, 0x0 },  // auto-detected
    { static_0_8005D310, 0x5CF10, 0x0 },  // auto-detected
    { static_0_8005EEFC, 0x5EAFC, 0x0 },  // auto-detected
    { static_0_8005F31C, 0x5EF1C, 0x0 },  // auto-detected
    { static_0_800600A0, 0x5FCA0, 0x0 },  // auto-detected
    { static_0_80060668, 0x60268, 0x0 },  // auto-detected
    { static_0_80063344, 0x62F44, 0x0 },  // auto-detected
    { static_0_8006373C, 0x6333C, 0x0 },  // auto-detected
    { static_0_80063AE0, 0x636E0, 0x0 },  // auto-detected
    { static_0_80063D0C, 0x6390C, 0x0 },  // auto-detected
    { static_0_80063EF4, 0x63AF4, 0x0 },  // auto-detected
    { static_0_80064034, 0x63C34, 0x0 },  // auto-detected
    { static_0_80064A88, 0x64688, 0x0 },  // auto-detected
    { static_0_80064AF4, 0x646F4, 0x0 },  // auto-detected
    { static_0_80064B44, 0x64744, 0x0 },  // auto-detected
    { static_0_80065804, 0x65404, 0x0 },  // auto-detected
    { static_0_80065C98, 0x65898, 0x0 },  // auto-detected
    { static_0_80065CB0, 0x658B0, 0x0 },  // auto-detected
    { static_0_80065E18, 0x65A18, 0x0 },  // auto-detected
    { static_0_80066144, 0x65D44, 0x0 },  // auto-detected
    { static_0_80067C70, 0x67870, 0x0 },  // auto-detected
    { static_0_8006A49C, 0x6A09C, 0x0 },  // auto-detected
    { static_0_8006ABD0, 0x6A7D0, 0x0 },  // auto-detected
    { static_0_8006B304, 0x6AF04, 0x0 },  // auto-detected
    { static_0_8006BC74, 0x6B874, 0x0 },  // auto-detected
    { static_0_8006C6D0, 0x6C2D0, 0x0 },  // auto-detected
    { static_0_8006C708, 0x6C308, 0x0 },  // auto-detected
    { static_0_8006C828, 0x6C428, 0x0 },  // auto-detected
    { static_0_8006D0C0, 0x6CCC0, 0x0 },  // auto-detected
    { static_0_8006D7F0, 0x6D3F0, 0x0 },  // auto-detected
    { static_0_8006D9DC, 0x6D5DC, 0x0 },  // auto-detected
    { static_0_8006E1CC, 0x6DDCC, 0x0 },  // auto-detected
    { static_0_8006E2FC, 0x6DEFC, 0x0 },  // auto-detected
    { static_0_8006E42C, 0x6E02C, 0x0 },  // auto-detected
    { static_0_8006FED0, 0x6FAD0, 0x0 },  // auto-detected
    { static_0_80070E98, 0x70A98, 0x0 },  // auto-detected
    { static_0_8007134C, 0x70F4C, 0x0 },  // auto-detected
    { static_0_80071820, 0x71420, 0x0 },  // auto-detected
    { static_0_800736AC, 0x732AC, 0x0 },  // auto-detected
    { static_0_80073708, 0x73308, 0x0 },  // auto-detected
    { static_0_80073834, 0x73434, 0x0 },  // auto-detected
    { static_0_80073C58, 0x73858, 0x0 },  // auto-detected
    { static_0_80075490, 0x75090, 0x0 },  // auto-detected
    { static_0_80075940, 0x75540, 0x0 },  // auto-detected
    { static_0_80076B34, 0x76734, 0x0 },  // auto-detected
    { static_0_80077054, 0x76C54, 0x0 },  // auto-detected
    { static_0_800784F8, 0x780F8, 0x0 },  // auto-detected
    { static_0_80079824, 0x79424, 0x0 },  // auto-detected
    { static_0_8007B41C, 0x7B01C, 0x0 },  // auto-detected
    { static_0_8007B7BC, 0x7B3BC, 0x0 },  // auto-detected
    { static_0_8007BA9C, 0x7B69C, 0x0 },  // auto-detected
    { static_0_8007BB28, 0x7B728, 0x0 },  // auto-detected
    { static_0_8007CD50, 0x7C950, 0x0 },  // auto-detected
    { static_0_8007DA20, 0x7D620, 0x0 },  // auto-detected
    { static_0_8007E988, 0x7E588, 0x0 },  // auto-detected
    { static_0_8007EE40, 0x7EA40, 0x0 },  // auto-detected
    { static_0_8007EE98, 0x7EA98, 0x0 },  // auto-detected
    { static_0_8007F22C, 0x7EE2C, 0x0 },  // auto-detected
    { static_0_8007F23C, 0x7EE3C, 0x0 },  // auto-detected
    { static_0_8007F914, 0x7F514, 0x0 },  // auto-detected
    { static_0_8007FD98, 0x7F998, 0x0 },  // auto-detected
    { static_0_80080148, 0x7FD48, 0x0 },  // auto-detected
    { static_0_800801B8, 0x7FDB8, 0x0 },  // auto-detected
    { static_0_80080350, 0x7FF50, 0x0 },  // auto-detected
    { static_0_80080D08, 0x80908, 0x0 },  // auto-detected
    { static_0_80080DB4, 0x809B4, 0x0 },  // auto-detected
    { static_0_800811C0, 0x80DC0, 0x0 },  // auto-detected
    { static_0_800811CC, 0x80DCC, 0x0 },  // auto-detected
    { static_0_80081260, 0x80E60, 0x0 },  // auto-detected
    { static_0_800812E8, 0x80EE8, 0x0 },  // auto-detected
    { static_0_80081360, 0x80F60, 0x0 },  // auto-detected
    { static_0_80081530, 0x81130, 0x0 },  // auto-detected
    { static_0_80081700, 0x81300, 0x0 },  // auto-detected
    { static_0_80081730, 0x81330, 0x0 },  // auto-detected
    { static_0_800819A4, 0x815A4, 0x0 },  // auto-detected
    { static_0_80081A2C, 0x8162C, 0x0 },  // auto-detected
    { static_0_800827C0, 0x823C0, 0x0 },  // auto-detected
    { static_0_80082BE0, 0x827E0, 0x0 },  // auto-detected
    { static_0_800834DC, 0x830DC, 0x0 },  // auto-detected
    { static_0_800834F0, 0x830F0, 0x0 },  // auto-detected
    { static_0_800845A0, 0x841A0, 0x0 },  // auto-detected
    { static_0_80084C30, 0x84830, 0x0 },  // auto-detected
    { static_0_80084D44, 0x84944, 0x0 },  // auto-detected
    { static_0_80084EB8, 0x84AB8, 0x0 },  // auto-detected
    { static_0_8008528C, 0x84E8C, 0x0 },  // auto-detected
    { static_0_80085AB4, 0x856B4, 0x0 },  // auto-detected
    { static_0_80085D44, 0x85944, 0x0 },  // auto-detected
    { static_0_80085E20, 0x85A20, 0x0 },  // auto-detected
    { static_0_80085F78, 0x85B78, 0x0 },  // auto-detected
    { static_0_80086178, 0x85D78, 0x0 },  // auto-detected
    { static_0_800862D8, 0x85ED8, 0x0 },  // auto-detected
    { static_0_8008635C, 0x85F5C, 0x0 },  // auto-detected
    { static_0_800863C8, 0x85FC8, 0x0 },  // auto-detected
    { static_0_80086730, 0x86330, 0x0 },  // auto-detected
    { static_0_8008681C, 0x8641C, 0x0 },  // auto-detected
    { static_0_80086930, 0x86530, 0x0 },  // auto-detected
    { static_0_80086CC8, 0x868C8, 0x0 },  // auto-detected
    { static_0_80086CE0, 0x868E0, 0x0 },  // auto-detected
    { static_0_80087080, 0x86C80, 0x0 },  // auto-detected
    { static_0_80087814, 0x87414, 0x0 },  // auto-detected
    { static_0_800879B8, 0x875B8, 0x0 },  // auto-detected
    { static_0_80087FC0, 0x87BC0, 0x0 },  // auto-detected
    { static_0_80088020, 0x87C20, 0x0 },  // auto-detected
    { static_0_80088050, 0x87C50, 0x0 },  // auto-detected
    { static_0_800880AC, 0x87CAC, 0x0 },  // auto-detected
    { static_0_800880E0, 0x87CE0, 0x0 },  // auto-detected
    { static_0_80088110, 0x87D10, 0x0 },  // auto-detected
    { static_0_80088150, 0x87D50, 0x0 },  // auto-detected
    { static_0_800883E0, 0x87FE0, 0x0 },  // auto-detected
    { static_0_80088B00, 0x88700, 0x0 },  // auto-detected
    { static_0_80089290, 0x88E90, 0x0 },  // auto-detected
    { static_0_800894D0, 0x890D0, 0x0 },  // auto-detected
    { static_0_80089570, 0x89170, 0x0 },  // auto-detected
    { static_0_80089590, 0x89190, 0x0 },  // auto-detected
    { static_0_800895E0, 0x891E0, 0x0 },  // auto-detected
    { static_0_800899E0, 0x895E0, 0x0 },  // auto-detected
    { static_0_80089C34, 0x89834, 0x0 },  // auto-detected
    { static_0_80089CC0, 0x898C0, 0x0 },  // auto-detected
    { static_0_8008A750, 0x8A350, 0x0 },  // auto-detected
    { static_0_8008A8C0, 0x8A4C0, 0x0 },  // auto-detected
    { static_0_8008AB48, 0x8A748, 0x0 },  // auto-detected
    { static_0_8008AB84, 0x8A784, 0x0 },  // auto-detected
    { static_0_8008AC48, 0x8A848, 0x0 },  // auto-detected
    { static_0_8008ADA0, 0x8A9A0, 0x0 },  // auto-detected
    { static_0_8008BF3C, 0x8BB3C, 0x0 },  // auto-detected
    { static_0_8008C2F0, 0x8BEF0, 0x0 },  // auto-detected
    { static_0_8008C738, 0x8C338, 0x0 },  // auto-detected
    { static_0_8008C900, 0x8C500, 0x0 },  // auto-detected
    { static_0_8008CA80, 0x8C680, 0x0 },  // auto-detected
    { static_0_8008CAA0, 0x8C6A0, 0x0 },  // auto-detected
    { static_0_8008CAC0, 0x8C6C0, 0x0 },  // auto-detected
    { static_0_8008D22C, 0x8CE2C, 0x0 },  // auto-detected
    { static_0_8008D274, 0x8CE74, 0x0 },  // auto-detected
    { static_0_8008D410, 0x8D010, 0x0 },  // auto-detected
    { static_0_8008D420, 0x8D020, 0x0 },  // auto-detected
    { static_0_80090500, 0x90100, 0x0 },  // auto-detected
    { static_0_800905F0, 0x901F0, 0x0 },  // auto-detected
    { static_0_80091630, 0x91230, 0x0 },  // auto-detected
    { static_0_80091B68, 0x91768, 0x0 },  // auto-detected
    { static_0_80092250, 0x91E50, 0x0 },  // auto-detected
    { static_0_80092850, 0x92450, 0x0 },  // auto-detected
    { static_0_80093820, 0x93420, 0x0 },  // auto-detected
    { static_0_80093890, 0x93490, 0x0 },  // auto-detected
    { static_0_800938F0, 0x934F0, 0x0 },  // auto-detected
    { static_0_80093980, 0x93580, 0x0 },  // auto-detected
    { static_0_80093990, 0x93590, 0x0 },  // auto-detected
    { static_0_80093A60, 0x93660, 0x0 },  // auto-detected
    { static_0_80093A90, 0x93690, 0x0 },  // auto-detected
    { static_0_80093C00, 0x93800, 0x0 },  // auto-detected
    { static_0_80093C10, 0x93810, 0x0 },  // auto-detected
    { static_0_80093C20, 0x93820, 0x0 },  // auto-detected
    { static_0_80093DB0, 0x939B0, 0x0 },  // auto-detected
    { static_0_80093E3C, 0x93A3C, 0x0 },  // auto-detected
    { static_0_800941B0, 0x93DB0, 0x0 },  // auto-detected
    { static_0_800941D0, 0x93DD0, 0x0 },  // auto-detected
};

SectionTableEntry section_table[] = {
    {
        0x1000,  // rom_addr
        0x80000400,  // ram_addr
        0x98000,  // size
        section_funcs,  // funcs
        1402,  // num_funcs
        nullptr,  // relocs (none for static code)
        0,  // num_relocs
        0,  // index
    },
};

extern const size_t num_sections = 1;
